apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: file-system
  namespace: default
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: musical-spoon
  targetCPUUtilizationPercentage: 80
