# YAML for changing the resources requests and/or limits of the deployment in PROD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-system
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: file-system
