# YAML for adding/replacing environment variables
# This is an example of adding/replacing objects in an array of objects
# The objects are located in the array by an undocumented kustomize feature that locates them by a certain key value
# In this case the key value is the name of the env var and it must be the first item in each object
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-system
spec:
  template:
    spec:
      containers:
        - name: file-system

          env:
            - name: NODE_ENV
              value: staging

            - name: S3_BUCKET
              value: vatbox-bucket-staging

            - name: INCOMING_PRIMARY_FOLDER
              value: IncomingFiles

            - name: INCOMING_SECONDARY_FOLDER
              value: SemiProcessedFiles

            - name: OUTGOING_FOLDER
              value: FurtherProcessingFiles

            - name: MONGNO_URL
              value: placeholder

            - name: IMAGINARY_UPLOAD_URL
              value: http://imaginary/api/exposed/v1.0/asset

            - name: TEST_ENV_VAR
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

