# YAML for setting the image in STAG
# Placed in a patch in order to allow different images for production and staging
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-system
spec:
  template:
    spec:
      containers:
        - name: file-system
          image: 'IMAGE_NAME'
