# YAML for changing the resources requests and/or limits of the deployment in STAG
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-system
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: musical-spoon
